---
# Backend Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-service-config
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: backend
    environment: ${ENV}
data:
  # API Server Settings
  API_PORT: "8000"
  API_WORKERS: "4"
  API_TIMEOUT: "30"
  MAX_REQUEST_SIZE: "10MB"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW: "60"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Security Settings
  CORS_ORIGINS: "https://*.sales-intelligence.com"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Service Integration Endpoints
  KAFKA_BROKERS: "kafka-headless.kafka.svc.cluster.local:9092"
  REDIS_HOST: "redis-master.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  ELASTICSEARCH_HOST: "elasticsearch-master.elasticsearch.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  
  # Operational Settings
  GRACEFUL_SHUTDOWN_TIMEOUT: "30"

---
# AI Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-config
  namespace: sales-intelligence-ai
  labels:
    app: sales-intelligence-platform
    component: ai
    environment: ${ENV}
data:
  # Server Settings
  MODEL_SERVER_PORT: "8001"
  MODEL_TIMEOUT: "60"
  INFERENCE_WORKERS: "2"
  
  # Model Configuration
  MODEL_BATCH_SIZE: "32"
  MODEL_CACHE_SIZE: "1024"
  MODEL_VERSION_PATH: "/models"
  MODEL_RELOAD_INTERVAL: "3600"
  
  # GPU Settings
  GPU_ENABLED: "true"
  GPU_MEMORY_FRACTION: "0.8"
  TENSOR_PARALLEL_DEGREE: "2"
  
  # Queue Management
  MAX_QUEUE_SIZE: "1000"
  INFERENCE_TIMEOUT: "30"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Operational Settings
  GRACEFUL_SHUTDOWN_TIMEOUT: "60"

---
# Analytics Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: analytics
    environment: ${ENV}
data:
  # Server Settings
  ANALYTICS_PORT: "8002"
  ANALYTICS_WORKERS: "4"
  QUERY_TIMEOUT: "30"
  MAX_CONCURRENT_QUERIES: "50"
  
  # Data Processing
  AGGREGATION_BATCH_SIZE: "1000"
  EXPORT_BATCH_SIZE: "5000"
  REPORT_CACHE_TTL: "3600"
  
  # Data Retention
  METRICS_RETENTION_DAYS: "90"
  DATA_ARCHIVE_AGE_DAYS: "365"
  REAL_TIME_METRICS_WINDOW: "300"
  
  # Service Integration
  CLICKHOUSE_HOST: "clickhouse-headless.clickhouse.svc.cluster.local"
  CLICKHOUSE_PORT: "9000"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Operational Settings
  GRACEFUL_SHUTDOWN_TIMEOUT: "30"