---
# PostgreSQL Database Credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: database
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  POSTGRES_USER: ${BASE64_POSTGRES_USER}
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}
  POSTGRES_DB: ${BASE64_POSTGRES_DB}
  POSTGRES_HOST: ${BASE64_POSTGRES_HOST}
  POSTGRES_PORT: ${BASE64_POSTGRES_PORT}
  POSTGRES_SSL_MODE: ${BASE64_POSTGRES_SSL_MODE}
  POSTGRES_CONNECTION_TIMEOUT: ${BASE64_POSTGRES_CONNECTION_TIMEOUT}
---
# LinkedIn Ads API Credentials
apiVersion: v1
kind: Secret
metadata:
  name: linkedin-credentials
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: integration
    platform: linkedin
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  LINKEDIN_CLIENT_ID: ${BASE64_LINKEDIN_CLIENT_ID}
  LINKEDIN_CLIENT_SECRET: ${BASE64_LINKEDIN_CLIENT_SECRET}
  LINKEDIN_ACCESS_TOKEN: ${BASE64_LINKEDIN_ACCESS_TOKEN}
  LINKEDIN_REFRESH_TOKEN: ${BASE64_LINKEDIN_REFRESH_TOKEN}
  LINKEDIN_API_VERSION: ${BASE64_LINKEDIN_API_VERSION}
  LINKEDIN_CALLBACK_URL: ${BASE64_LINKEDIN_CALLBACK_URL}
---
# Google Ads API Credentials
apiVersion: v1
kind: Secret
metadata:
  name: google-ads-credentials
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: integration
    platform: google-ads
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  GOOGLE_ADS_CLIENT_ID: ${BASE64_GOOGLE_ADS_CLIENT_ID}
  GOOGLE_ADS_CLIENT_SECRET: ${BASE64_GOOGLE_ADS_CLIENT_SECRET}
  GOOGLE_ADS_DEVELOPER_TOKEN: ${BASE64_GOOGLE_ADS_DEVELOPER_TOKEN}
  GOOGLE_ADS_REFRESH_TOKEN: ${BASE64_GOOGLE_ADS_REFRESH_TOKEN}
  GOOGLE_ADS_LOGIN_CUSTOMER_ID: ${BASE64_GOOGLE_ADS_LOGIN_CUSTOMER_ID}
  GOOGLE_ADS_API_VERSION: ${BASE64_GOOGLE_ADS_API_VERSION}
  GOOGLE_ADS_CALLBACK_URL: ${BASE64_GOOGLE_ADS_CALLBACK_URL}
---
# Auth0 Authentication Credentials
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: auth
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  AUTH0_DOMAIN: ${BASE64_AUTH0_DOMAIN}
  AUTH0_CLIENT_ID: ${BASE64_AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${BASE64_AUTH0_CLIENT_SECRET}
  AUTH0_AUDIENCE: ${BASE64_AUTH0_AUDIENCE}
  AUTH0_CALLBACK_URL: ${BASE64_AUTH0_CALLBACK_URL}
  AUTH0_LOGOUT_URL: ${BASE64_AUTH0_LOGOUT_URL}
---
# JWT Token Configuration
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: sales-intelligence-backend
  labels:
    app: sales-intelligence-platform
    component: auth
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  JWT_SECRET_KEY: ${BASE64_JWT_SECRET_KEY}
  JWT_ALGORITHM: ${BASE64_JWT_ALGORITHM}
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${BASE64_JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: ${BASE64_JWT_REFRESH_TOKEN_EXPIRE_DAYS}