apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: monitoring
    part-of: sales-intelligence-platform
    managed-by: kubernetes
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    description: 'Grafana monitoring dashboard service for Sales Intelligence Platform'
    maintainer: 'platform-team'
spec:
  selector:
    app: grafana
  ports:
    - name: grafana-ui
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: false