version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
        NEXT_TELEMETRY_DISABLED: '1'
    container_name: sales-intelligence-web
    ports:
      - "3000:3000"  # Next.js application
      - "9229:9229"  # Node.js debugging
    volumes:
      - .:/app:delegated  # Source code for hot reloading
      - node_modules:/app/node_modules  # Persistent dependencies
      - next-cache:/app/.next  # Build cache
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_WEBPACK_USEPOLLING=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_VERSION=v1
      - NEXT_PUBLIC_APP_ENV=development
      - NEXT_PUBLIC_APP_NAME=Sales & Intelligence Platform
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  node_modules:
    name: sales-intelligence-node-modules
  next-cache:
    name: sales-intelligence-next-cache

networks:
  app-network:
    name: sales-intelligence-network
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: sales-intelligence-bridge
    labels:
      environment: development